### PR TITLE
Added New Pytests for bucket_create and listing only directory

### PR DESCRIPTION
**Pull request by jkandima**
Expanded def bucket_create function for logging metadata and updating the MongoDB
Fixed the def list function to search for dir only and all bucket
Created new Pytests for bucket_create and listing only directory in def list.

### CODE REVIEW

**Comment by jkandima** [comment]
> cloudmesh/storage/Provider.py
> 
> bucket create is a special aws3 feature, thus it must not be in tha general class

Hi Professor, Do you want me to remove the pytest

**Comment by laszewsk** [comment]
This is for cloudmesh/storage/Provider.py 

which is wrong. bucket create can not be in the general provider, there we only have directory create

**Comment by jkandima** [comment]
> This is for cloudmesh/storage/Provider.py
> 
> which is wrong. bucket create can not be in the general provider, there we only have directory create

yes professor you are right but in order to execute the pytest from general provider if i dont have function i cannot me called or cannot use mongodb to store the metadata.

**Comment by laszewsk** [comment]
that function can only be in your cloud provider not in the storage provider. in teh storage provider you need an if condition that than calls either bucket create or directory create the storage provider thus only has a directory create and in your directory create for your provider you do what is needed with an if condition.

**Comment by jkandima** [comment]
> This is still not right as there must not be any reference to aws in the test as this test is used for all providers.
> 
> cms set storage=aws
> pytest tests/test_storsge.py
> 
> cms set storage=azure
> pytest tests/test_storsge.py
> 
> and so on should work

i believe we should talk for 5 min,the bucket_create function is only in awss3 provider only,to test the function in pytest i have imported the awss3 provider to call the function.even though we don't have this pytest the bucket_create function will be tested in the create_dir function.If you think there is confusion in the pytest i can remove the pytest related to bucket_create

**Comment by laszewsk** [comment]
i am in zoom now

**Pull request merged**
